[package]
name = "framework-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
log = "0.4"
lazy_static = "1.5.0"
env_logger = "0.11"
